import type { Atom, AtomType, Capture, Question, Session } from "./types.js";

const TYPE_LABEL: Record<AtomType, string> = {
  procedure: "Procedures",
  rule: "Rules of thumb",
  gotcha: "Gotchas",
  contact: "People & contacts",
  tool: "Tools & reports",
  decision: "Judgement calls",
  glossary: "Glossary",
  risk: "Risks",
  story: "Stories worth keeping",
};

const TYPE_ORDER: AtomType[] = ["procedure", "rule", "gotcha", "risk", "decision", "contact", "tool", "glossary", "story"];

function fmtDate(iso?: string): string {
  if (!iso) return "";
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? iso : d.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
}

/** Compile a Markdown handover document from everything captured. */
export function compileHandover(capture: Capture, atoms: Atom[], sessions: Session[], questions: Question[]): string {
  const e = capture.expert;
  const lines: string[] = [];
  lines.push(`# Handover: ${e.role}`);
  lines.push("");
  lines.push(`**Expert:** ${e.name}${e.team ? ` · ${e.team}` : ""}${e.tenureYears ? ` · ${e.tenureYears} years in role` : ""}  `);
  if (e.departureDate) lines.push(`**Last day:** ${fmtDate(e.departureDate)}  `);
  if (capture.successor) lines.push(`**Prepared for:** ${capture.successor.name}${capture.successor.role ? ` (${capture.successor.role})` : ""}  `);
  lines.push(`**Captured:** ${atoms.length} knowledge atoms across ${sessions.length} session${sessions.length === 1 ? "" : "s"} · ${Math.round(capture.stats.coverage * 100)}% coverage  `);
  lines.push(`**Generated by Tacit** on ${fmtDate(new Date().toISOString())}`);
  lines.push("");
  lines.push("> This document was distilled from recorded interviews. Items marked ✓ were verified by the expert. Quotes are the expert's own words.");
  lines.push("");

  lines.push("## Coverage map");
  lines.push("");
  lines.push("| Domain | Priority | Coverage | Atoms |");
  lines.push("|---|---|---|---|");
  for (const d of [...capture.domains].sort((a, b) => a.priority - b.priority)) {
    lines.push(`| ${d.name} | P${d.priority} | ${Math.round(d.coverage * 100)}% | ${d.atomCount} |`);
  }
  lines.push("");

  const sortedDomains = [...capture.domains].sort((a, b) => a.priority - b.priority || b.atomCount - a.atomCount);
  const unassigned = atoms.filter((a) => !a.domainId || !capture.domains.some((d) => d.id === a.domainId));

  const renderAtoms = (list: Atom[]) => {
    for (const type of TYPE_ORDER) {
      const group = list.filter((a) => a.type === type);
      if (!group.length) continue;
      lines.push(`### ${TYPE_LABEL[type]}`);
      lines.push("");
      for (const a of group) {
        lines.push(`**${a.title}**${a.verified ? " ✓" : ""}`);
        lines.push("");
        lines.push(a.content.trim());
        if (a.sourceQuote) {
          lines.push("");
          lines.push(`> “${a.sourceQuote.trim()}” — ${e.name.split(" ")[0]}`);
        }
        if (a.tags.length) lines.push(`\n_Tags: ${a.tags.join(", ")}_`);
        lines.push("");
      }
    }
  };

  for (const d of sortedDomains) {
    const list = atoms.filter((a) => a.domainId === d.id);
    if (!list.length) continue;
    lines.push(`## ${d.name}`);
    lines.push("");
    lines.push(`_${d.description}_`);
    lines.push("");
    renderAtoms(list);
  }
  if (unassigned.length) {
    lines.push("## General");
    lines.push("");
    renderAtoms(unassigned);
  }

  const open = questions.filter((q) => q.status !== "answered" && q.source !== "plan");
  const uncovered = capture.domains.filter((d) => d.coverage < 0.4);
  if (open.length || uncovered.length) {
    lines.push("## Still open");
    lines.push("");
    for (const q of open) lines.push(`- ${q.text}${q.askedBy ? ` _(asked by ${q.askedBy})_` : ""}`);
    for (const d of uncovered) lines.push(`- Domain **${d.name}** is only ${Math.round(d.coverage * 100)}% covered.`);
    lines.push("");
  }

  if (sessions.length) {
    lines.push("## Session log");
    lines.push("");
    for (const s of [...sessions].sort((a, b) => a.startedAt.localeCompare(b.startedAt))) {
      lines.push(`- **${fmtDate(s.startedAt)}** · ${s.mode.replace("voice-", "voice · ")} · ${s.turnCount} turns · ${s.atomCount} atoms${s.summary ? ` — ${s.summary}` : ""}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}
